[tool.poetry]
name = "leetcode"
version = "0.1.0"
description = "Questões do LeetCode com tag `divide and conquer`."
authors = ["Guilherme Marques <marquesguilherme3@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pytest = "^8.3.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
